# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jogo - Create voice games
display_title: Jogo
seo:
  name: Jogo - Create voice games
  image:
    width: 630
email: info@jogo.gg
description: > # this means to ignore newlines until "baseurl:"
  Jogo makes creating voice games fun.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jogo.gg" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jogogoodgame
timezone: America/Denver
future: false
paginate: 6
paginate_path: "blog/:num/"
disqus:
  shortname: jogo
logo: "/assets/img/logo.png"
permalink: /:title/
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/logo.png
jekyll_compose:
  default_front_matter:
    posts:
      layout: post
      display_title: ""
      last_modified_at: 
      description: ""
      reading: "1 minute"
      image: /assets/img/
      image_svg: /assets/img/
      published: true
      sitemap: true
      tags: []
      display_excerpt: ""
collections:
  tags:
    output: true
    permalinks: /tags/:path/
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - amp-jekyll
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-compose
exclude:
  - Gemfile
  - Gemfile.lock